name: CI (web)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable Corepack
        run: corepack enable

      - name: Install deps (workspace, only web)
        run: pnpm install --frozen-lockfile --filter "web..."

      - name: Lint
        run: pnpm -F web lint

      - name: Build
        run: pnpm -F web build
        env:
          WP_GRAPHQL_ENDPOINT: https://dulcedesaigon.com/graphql
          NEXT_PUBLIC_SITE_URL: https://dulcedesaigon.com
          # If you ever need it in CI:
          # WP_PREVIEW_SECRET: ${{ secrets.WP_PREVIEW_SECRET }}
