name: CI (web)
on:
  push: { branches: [main] }
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: corepack enable
      - run: pnpm install --frozen-lockfile --filter "web..."
      - run: pnpm -F web lint
      - run: pnpm -F web typecheck
      - run: pnpm -F web build
        env:
          WP_GRAPHQL_ENDPOINT: https://dulcedesaigon.com/graphql
          NEXT_PUBLIC_SITE_URL: https://dulcedesaigon.com
